import java.sql.*;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Jatin Kamboj
 */
public class Stock extends javax.swing.JFrame {

    /**
     * Creates new form Stock
     */
    public Stock() {
        initComponents();
        ntf.setVisible(false);
        init();
    }

    public void init() {
        setLocationRelativeTo(null);
    }                    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        s_id = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        s_nm = new javax.swing.JTextField();
        t_id = new javax.swing.JTextField();
        d_dt = new javax.swing.JTextField();
        r_dt = new javax.swing.JTextField();
        rec = new javax.swing.JTextField();
        cons = new javax.swing.JTextField();
        submit1 = new javax.swing.JButton();
        modify = new javax.swing.JButton();
        remove = new javax.swing.JButton();
        search = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        back = new javax.swing.JButton();
        print = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        ntf = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Stock Management System");
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(0, 255, 153));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 51), 2, true));
        jPanel2.setToolTipText("Stock Management System");

        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Uttam Nagar, New Delhi");
        jLabel12.setToolTipText("Uttam Nagar, New Delhi");
        jLabel12.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel12.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jLabel12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel13.setFont(new java.awt.Font("Magneto", 1, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 0, 0));
        jLabel13.setText("Stock Management System");
        jLabel13.setToolTipText("Stock Management System");
        jLabel13.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel14.setFont(new java.awt.Font("Brush Script MT", 1, 22)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 0));
        jLabel14.setText("Stock ID");
        jLabel14.setToolTipText("Stock ID");

        s_id.setFont(new java.awt.Font("Baskerville Old Face", 1, 12)); // NOI18N
        s_id.setForeground(new java.awt.Color(0, 102, 102));
        s_id.setToolTipText("Enter Your Stock ID");

        jLabel15.setFont(new java.awt.Font("Brush Script MT", 1, 22)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 51, 0));
        jLabel15.setText("Stock Name");
        jLabel15.setToolTipText("Stock Name");

        jLabel16.setFont(new java.awt.Font("Brush Script MT", 1, 22)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 51, 0));
        jLabel16.setText("Transaction ID");
        jLabel16.setToolTipText("Transaction ID");

        jLabel17.setFont(new java.awt.Font("Brush Script MT", 1, 22)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 51, 0));
        jLabel17.setText("Receiving Date");
        jLabel17.setToolTipText("Receiving Date");

        jLabel18.setFont(new java.awt.Font("Brush Script MT", 1, 22)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(51, 51, 0));
        jLabel18.setText("Delivery Date");
        jLabel18.setToolTipText("Delivery Date");

        jLabel19.setFont(new java.awt.Font("Brush Script MT", 1, 22)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(51, 51, 0));
        jLabel19.setText("Received By");
        jLabel19.setToolTipText("Received By");

        jLabel20.setFont(new java.awt.Font("Brush Script MT", 1, 22)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(51, 51, 0));
        jLabel20.setText("Consigner");
        jLabel20.setToolTipText("Consigner");

        s_nm.setFont(new java.awt.Font("Baskerville Old Face", 1, 12)); // NOI18N
        s_nm.setForeground(new java.awt.Color(0, 102, 102));
        s_nm.setToolTipText("Enter Your Stock Name");

        t_id.setFont(new java.awt.Font("Baskerville Old Face", 1, 12)); // NOI18N
        t_id.setForeground(new java.awt.Color(0, 102, 102));
        t_id.setToolTipText("Enter Your Transaction ID");

        d_dt.setFont(new java.awt.Font("Baskerville Old Face", 1, 12)); // NOI18N
        d_dt.setForeground(new java.awt.Color(0, 102, 102));
        d_dt.setToolTipText("Enter Your Delivery Date");

        r_dt.setFont(new java.awt.Font("Baskerville Old Face", 1, 12)); // NOI18N
        r_dt.setForeground(new java.awt.Color(0, 102, 102));
        r_dt.setToolTipText("Enter Your Receiving Date");

        rec.setFont(new java.awt.Font("Baskerville Old Face", 1, 12)); // NOI18N
        rec.setForeground(new java.awt.Color(0, 102, 102));
        rec.setToolTipText("Enter Received By Person");

        cons.setFont(new java.awt.Font("Baskerville Old Face", 1, 12)); // NOI18N
        cons.setForeground(new java.awt.Color(0, 102, 102));
        cons.setToolTipText("Enter Your Consigner");

        submit1.setFont(new java.awt.Font("Script MT Bold", 3, 16)); // NOI18N
        submit1.setForeground(new java.awt.Color(75, 51, 0));
        submit1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ins.png"))); // NOI18N
        submit1.setToolTipText("Submit Your Record");
        submit1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 204, 255), new java.awt.Color(0, 204, 204), new java.awt.Color(204, 204, 255), new java.awt.Color(0, 255, 204)));
        submit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit1ActionPerformed(evt);
            }
        });

        modify.setFont(new java.awt.Font("Script MT Bold", 3, 16)); // NOI18N
        modify.setForeground(new java.awt.Color(75, 51, 0));
        modify.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/modify.png"))); // NOI18N
        modify.setToolTipText("Modify Your Record");
        modify.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 204, 255), new java.awt.Color(0, 204, 204), new java.awt.Color(204, 204, 255), new java.awt.Color(0, 255, 204)));
        modify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyActionPerformed(evt);
            }
        });

        remove.setFont(new java.awt.Font("Script MT Bold", 3, 16)); // NOI18N
        remove.setForeground(new java.awt.Color(75, 51, 0));
        remove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/remove.png"))); // NOI18N
        remove.setToolTipText("Remove Your Record");
        remove.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 204, 255), new java.awt.Color(0, 204, 204), new java.awt.Color(204, 204, 255), new java.awt.Color(0, 255, 204)));
        remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeActionPerformed(evt);
            }
        });

        search.setFont(new java.awt.Font("Script MT Bold", 3, 16)); // NOI18N
        search.setForeground(new java.awt.Color(75, 51, 0));
        search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/searchp.png"))); // NOI18N
        search.setToolTipText("Search Your Record");
        search.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 204, 255), new java.awt.Color(0, 204, 204), new java.awt.Color(204, 204, 255), new java.awt.Color(0, 255, 204)));
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        clear.setFont(new java.awt.Font("Script MT Bold", 3, 16)); // NOI18N
        clear.setForeground(new java.awt.Color(75, 51, 0));
        clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/clear.png"))); // NOI18N
        clear.setToolTipText("Clear All Inputs");
        clear.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 204, 255), new java.awt.Color(0, 204, 204), new java.awt.Color(204, 204, 255), new java.awt.Color(0, 255, 204)));
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        back.setFont(new java.awt.Font("Script MT Bold", 3, 16)); // NOI18N
        back.setForeground(new java.awt.Color(75, 51, 0));
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back.png"))); // NOI18N
        back.setToolTipText("Exit");
        back.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 204, 255), new java.awt.Color(0, 204, 204), new java.awt.Color(204, 204, 255), new java.awt.Color(0, 255, 204)));
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        print.setFont(new java.awt.Font("Script MT Bold", 3, 16)); // NOI18N
        print.setForeground(new java.awt.Color(75, 51, 0));
        print.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/print.png"))); // NOI18N
        print.setToolTipText("Print The Information");
        print.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 204, 255), new java.awt.Color(0, 204, 204), new java.awt.Color(204, 204, 255), new java.awt.Color(0, 255, 204)));
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/inventory-management.png"))); // NOI18N
        jLabel21.setToolTipText("Stock");

        ntf.setFont(new java.awt.Font("Brush Script MT", 3, 18)); // NOI18N
        ntf.setForeground(new java.awt.Color(102, 0, 0));
        ntf.setText("Notifications");
        ntf.setToolTipText("Notification");

        jLabel1.setBackground(new java.awt.Color(153, 255, 153));
        jLabel1.setFont(new java.awt.Font("Matura MT Script Capitals", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("RESOURCE MAINTENANCE & MANAGEMENT");
        jLabel1.setToolTipText("RESOURCE MAINTENANCE & MANAGEMENT");
        jLabel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 11), new java.awt.Color(51, 0, 102))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(459, 27));
        jLabel1.setMinimumSize(new java.awt.Dimension(469, 27));
        jLabel1.setPreferredSize(new java.awt.Dimension(469, 27));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(submit1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(94, 94, 94)
                        .addComponent(modify, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83)
                        .addComponent(remove, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79)
                        .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cons, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rec, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(d_dt, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(r_dt, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(t_id, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(s_id, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(76, 76, 76)
                                .addComponent(s_nm, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(print, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(363, 363, 363)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(297, 297, 297)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(101, 101, 101)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(ntf, javax.swing.GroupLayout.PREFERRED_SIZE, 697, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 677, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(s_id, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel14))
                            .addComponent(print))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(s_nm, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(t_id, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(r_dt, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(d_dt, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(rec, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cons, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20))
                        .addGap(104, 104, 104)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(modify)
                            .addComponent(submit1)
                            .addComponent(remove)
                            .addComponent(search)
                            .addComponent(clear)
                            .addComponent(back))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ntf, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(24, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel21)
                        .addGap(129, 129, 129))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit1ActionPerformed
        String sid,snm,tid,rdt,ddt,recv,conn;
        sid=s_id.getText();
        snm=s_nm.getText();
        tid=t_id.getText();
        rdt=r_dt.getText();
        ddt=d_dt.getText();
        recv=rec.getText();
        conn=cons.getText();
        if((sid!="")&&(snm!="")&&(tid!="")&&(rdt!="")&&(ddt!="")&&(recv!="")&&(conn!="")){
            try{
                Class.forName("oracle.jdbc.driver.OracleDriver");
                Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","resourcem","resourcem");
                Statement stmt=con.createStatement();
                int a=stmt.executeUpdate("insert into STOCK values('"+sid+"','"+snm+"','"+tid+"','"+rdt+"','"+ddt+"','"+recv+"','"+conn+"')");
                con.close();
                ntf.setVisible(true);
                ntf.setText("Record Successfully Inserted...!!");
                s_id.setText("");
                s_nm.setText("");
                t_id.setText("");
                r_dt.setText("");
                d_dt.setText("");
                rec.setText("");
                cons.setText("");
            }catch(Exception e){
                e.printStackTrace();
                ntf.setVisible(true);
                ntf.setText("An Error Has Been Occurred While Inserting The Record...!!");
            }
        }else{
            ntf.setVisible(true);
            ntf.setText("Some of the Given Fields is Empty.Please Fill them Properly and Try Again Later...!!");
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_submit1ActionPerformed

    private void modifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyActionPerformed
        String sid,snm,tid,rdt,ddt,recv,conn;
        sid=s_id.getText();
        snm=s_nm.getText();
        tid=t_id.getText();
        rdt=r_dt.getText();
        ddt=d_dt.getText();
        recv=rec.getText();
        conn=cons.getText();
        if((sid!="")&&(snm!="")&&(tid!="")&&(rdt!="")&&(ddt!="")&&(recv!="")&&(conn!="")){
            try{
                Class.forName("oracle.jdbc.driver.OracleDriver");
                Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","resourcem","resourcem");
                Statement stmt=con.createStatement();
                int a=stmt.executeUpdate("update STOCK set S_NAME='"+snm+"',TR_ID='"+tid+"',REC_DT='"+rdt+"',DEL_DT='"+ddt+"',REC='"+recv+"',CONSI='"+conn+"' where S_ID='"+sid+"' ");
                con.close();
                ntf.setVisible(true);
                ntf.setText("Record Successfully Modified...!!");
                s_id.setText("");
                s_nm.setText("");
                t_id.setText("");
                r_dt.setText("");
                d_dt.setText("");
                rec.setText("");
                cons.setText("");
            }catch(Exception e){
                //e.printStackTrace();
                ntf.setVisible(true);
                ntf.setText("An Error Has Been Occurred While Modifying The Record...!!");
            }
        }else{
            ntf.setVisible(true);
            ntf.setText("Some of the Given Field's is Empty.Please Fill them Properly and Try Again Later...!!");
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_modifyActionPerformed

    private void removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeActionPerformed
        String sid=s_id.getText();
        if(sid!=""){
            try{
                Class.forName("oracle.jdbc.driver.OracleDriver");
                Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","resourcem","resourcem");
                Statement stmt=con.createStatement();
                int a=stmt.executeUpdate("delete from STOCK where S_ID='"+sid+"'");
                ntf.setVisible(true);
                ntf.setText("Record Successfully Removed...!!");
                s_id.setText("");
                s_nm.setText("");
                t_id.setText("");
                r_dt.setText("");
                d_dt.setText("");
                rec.setText("");
                cons.setText("");
                con.close();
            }catch(Exception e){
                e.printStackTrace();
                ntf.setVisible(true);
                ntf.setText("An Error Has Been Occurred While Removing The Reocrd...!!");
            }
        }else{
            ntf.setVisible(true);
            ntf.setText("Plese Enter the Customer ID First...!!");
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_removeActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        String sid=s_id.getText();
        if(sid!=""){
            try{
                Class.forName("oracle.jdbc.driver.OracleDriver");
                Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","resourcem","resourcem");
                Statement stmt=con.createStatement();
                ResultSet rs=stmt.executeQuery("select * from STOCK where S_ID='"+sid+"'");
                if(rs.next()){
                    ntf.setVisible(true);
                    ntf.setText("Record is Available...!!");
                    s_nm.setText(rs.getString(2));
                    t_id.setText(rs.getString(3));
                    r_dt.setText(rs.getString(4));
                    d_dt.setText(rs.getString(5));
                    rec.setText(rs.getString(6));
                    cons.setText(rs.getString(7));
                }else{
                    ntf.setVisible(true);
                    ntf.setText("Record isn't Available...!!");
                }
                con.close();
            }catch(Exception e){
                e.printStackTrace();
                ntf.setVisible(true);
                ntf.setText("An Error Has Been Occurred While Searching The Record...!!");
            }
        }else{
            ntf.setVisible(true);
            ntf.setText("Please Enter the Customer ID First...!!");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_searchActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        s_id.setText("");
        s_nm.setText("");
        t_id.setText("");
        r_dt.setText("");
        d_dt.setText("");
        rec.setText("");
        cons.setText("");
        ntf.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_clearActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        dispose();
        main obj231=new main();
        obj231.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_backActionPerformed

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
        ntf.setVisible(true);
        ntf.setText("Please First Installed The Printer With Software...!!");
        // TODO add your handling code here:
    }//GEN-LAST:event_printActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Stock().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton clear;
    private javax.swing.JTextField cons;
    private javax.swing.JTextField d_dt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JButton modify;
    private javax.swing.JLabel ntf;
    private javax.swing.JButton print;
    private javax.swing.JTextField r_dt;
    private javax.swing.JTextField rec;
    public javax.swing.JButton remove;
    private javax.swing.JTextField s_id;
    private javax.swing.JTextField s_nm;
    public javax.swing.JButton search;
    public javax.swing.JButton submit1;
    private javax.swing.JTextField t_id;
    // End of variables declaration//GEN-END:variables
}
