import java.sql.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Jatin Kamboj
 */
public class usrreg extends javax.swing.JFrame {

    /**
     * Creates new form usrreg
     */
    public usrreg() {
        initComponents();
        init();
        ntf.setVisible(false);
    }
    public void init() {
        setLocationRelativeTo(null);
    }        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        ntf = new javax.swing.JLabel();
        createnew = new javax.swing.JButton();
        alreadyac = new javax.swing.JButton();
        usrnm = new javax.swing.JTextField();
        nm = new javax.swing.JTextField();
        ans = new javax.swing.JTextField();
        usrpss = new javax.swing.JPasswordField();
        usrrepss = new javax.swing.JPasswordField();
        ques = new javax.swing.JComboBox<>();
        usrtyp = new javax.swing.JTextField();
        clear = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("User Registration");
        setMinimumSize(new java.awt.Dimension(300, 500));
        setName("Registration"); // NOI18N
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 51), 1, true));
        jPanel1.setToolTipText("Create New Account");

        jLabel9.setFont(new java.awt.Font("Magneto", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 0, 0));
        jLabel9.setText(" Create An Account :-");
        jLabel9.setToolTipText(" Create An Account");
        jLabel9.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/qJllMxITr1_ETwiPvt-ksXNI5s1QWTA_o7LKjasRJ80hHgWK2hTE-tZSAtRHffmPMkd2qiSfnssObfeYwaKXpNeL2QNwUuF6TEtEgSO9hMEdgQ=w406-h362-nc.jpg"))); // NOI18N
        jLabel3.setToolTipText("User Registration");

        jLabel4.setFont(new java.awt.Font("Brush Script MT", 1, 22)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 0));
        jLabel4.setText("Name");
        jLabel4.setToolTipText("Name");

        jLabel6.setFont(new java.awt.Font("Brush Script MT", 1, 22)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 0));
        jLabel6.setText("Password ");
        jLabel6.setToolTipText("Password ");

        jLabel7.setFont(new java.awt.Font("Brush Script MT", 1, 22)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 0));
        jLabel7.setText("User Name");
        jLabel7.setToolTipText("User Name");

        jLabel8.setFont(new java.awt.Font("Brush Script MT", 1, 22)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 0));
        jLabel8.setText("Re-Enter Password ");
        jLabel8.setToolTipText("Re-Enter Password ");

        jLabel10.setFont(new java.awt.Font("Brush Script MT", 1, 22)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 0));
        jLabel10.setText("Security Question ");
        jLabel10.setToolTipText("Security Question ");

        jLabel11.setFont(new java.awt.Font("Brush Script MT", 1, 22)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 0));
        jLabel11.setText("Security Answer ");
        jLabel11.setToolTipText("Security Answer ");

        jLabel12.setFont(new java.awt.Font("Brush Script MT", 1, 22)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 0));
        jLabel12.setText("U_Type ");
        jLabel12.setToolTipText("U_Type ");

        ntf.setFont(new java.awt.Font("Magneto", 3, 16)); // NOI18N
        ntf.setForeground(new java.awt.Color(102, 0, 0));
        ntf.setText("Notification");
        ntf.setToolTipText("Notification");

        createnew.setFont(new java.awt.Font("Script MT Bold", 3, 16)); // NOI18N
        createnew.setForeground(new java.awt.Color(102, 0, 0));
        createnew.setText("Create New Account");
        createnew.setToolTipText("Create New Account");
        createnew.setAutoscrolls(true);
        createnew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createnewActionPerformed(evt);
            }
        });

        alreadyac.setFont(new java.awt.Font("Script MT Bold", 3, 16)); // NOI18N
        alreadyac.setForeground(new java.awt.Color(102, 0, 0));
        alreadyac.setText("Already Have An Account");
        alreadyac.setToolTipText("Already Have An Account");
        alreadyac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alreadyacActionPerformed(evt);
            }
        });

        usrnm.setFont(new java.awt.Font("Baskerville Old Face", 3, 12)); // NOI18N
        usrnm.setForeground(new java.awt.Color(0, 102, 102));
        usrnm.setToolTipText("Enter your User Name");
        usrnm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usrnmActionPerformed(evt);
            }
        });

        nm.setFont(new java.awt.Font("Baskerville Old Face", 3, 12)); // NOI18N
        nm.setForeground(new java.awt.Color(0, 102, 102));
        nm.setToolTipText("Enter your Name");
        nm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nmActionPerformed(evt);
            }
        });

        ans.setFont(new java.awt.Font("Baskerville Old Face", 3, 12)); // NOI18N
        ans.setForeground(new java.awt.Color(0, 102, 102));
        ans.setToolTipText("Enter your Security Answer");
        ans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ansActionPerformed(evt);
            }
        });

        usrpss.setFont(new java.awt.Font("Baskerville Old Face", 3, 12)); // NOI18N
        usrpss.setForeground(new java.awt.Color(0, 102, 102));
        usrpss.setToolTipText("Enter your Password");

        usrrepss.setFont(new java.awt.Font("Baskerville Old Face", 3, 12)); // NOI18N
        usrrepss.setForeground(new java.awt.Color(0, 102, 102));
        usrrepss.setToolTipText("Re-Enter your Password");

        ques.setFont(new java.awt.Font("Magneto", 3, 11)); // NOI18N
        ques.setForeground(new java.awt.Color(204, 51, 0));
        ques.setMaximumRowCount(3);
        ques.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-----Select Any One-----", "What is your Nick Name?", "What is your Pet Name?", "What is your Best Friend Name?", "Who is your Ideal?", "What is your Aimbition?" }));
        ques.setToolTipText("Select Any One Question");

        usrtyp.setFont(new java.awt.Font("Baskerville Old Face", 3, 12)); // NOI18N
        usrtyp.setForeground(new java.awt.Color(0, 102, 102));
        usrtyp.setToolTipText("Enter User Type");
        usrtyp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usrtypActionPerformed(evt);
            }
        });

        clear.setFont(new java.awt.Font("Script MT Bold", 3, 16)); // NOI18N
        clear.setForeground(new java.awt.Color(102, 0, 0));
        clear.setText("Clear");
        clear.setToolTipText("Clear All Inputs");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(153, 255, 153));
        jLabel1.setFont(new java.awt.Font("Matura MT Script Capitals", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("RESOURCE MAINTENANCE & MANAGEMENT");
        jLabel1.setToolTipText("RESOURCE MAINTENANCE & MANAGEMENT");
        jLabel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 11), new java.awt.Color(51, 0, 102))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(459, 27));
        jLabel1.setMinimumSize(new java.awt.Dimension(469, 27));
        jLabel1.setPreferredSize(new java.awt.Dimension(469, 27));

        jLabel13.setFont(new java.awt.Font("Magneto", 1, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 153));
        jLabel13.setText("Uttam Nagar,New Delhi");
        jLabel13.setToolTipText("Uttam Nagar,New Delhi");
        jLabel13.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel13))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(75, 75, 75)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(29, 29, 29))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(18, 18, 18)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(usrrepss)
                                    .addComponent(usrpss)
                                    .addComponent(usrnm, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nm, javax.swing.GroupLayout.Alignment.LEADING)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel12))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ques, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(usrtyp)
                                    .addComponent(ans, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)))
                .addComponent(jLabel3))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(createnew)
                        .addGap(50, 50, 50)
                        .addComponent(alreadyac)
                        .addGap(76, 76, 76)
                        .addComponent(clear))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 677, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ntf, javax.swing.GroupLayout.PREFERRED_SIZE, 899, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(69, 69, 69))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(usrnm, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nm, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(usrpss, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(usrrepss, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ques, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ans, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(usrtyp, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(createnew)
                            .addComponent(alreadyac)
                            .addComponent(clear))))
                .addComponent(ntf, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 960, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createnewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createnewActionPerformed
        String s1,s2,s3,s4,s5,s6,s7;
        s1=usrnm.getText();
        s2=nm.getText();
        s3=usrpss.getText();
        s4=usrrepss.getText();
        s5=(String) ques.getSelectedItem();
        s6=ans.getText();
        s7=usrtyp.getText();
        if((s1!="")&&(s2!="")&&(s3!="")&&(s4!="")&&(s6!="")&&(s7!="")&&(s5!="")){
            if(s3.equals(s4)){
                try{
                    Class.forName("oracle.jdbc.driver.OracleDriver");
                    Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","RESOURCEM","RESOURCEM");
                    Statement stmt=con.createStatement();
                    int a=stmt.executeUpdate("insert into USR (USRNM,NAME,PASSWORD,SEC_QUES,SEC_ANS,U_TYP) values ('"+s1+"','"+s2+"','"+s3+"','"+s5+"','"+s6+"','"+s7+"')");
                    con.close();
                }catch(Exception e){
                    e.printStackTrace();
                    ntf.setVisible(true);
                    ntf.setText("A Problem Has Been Occurred While Creating A New User.Please Try Again...!!");
                }
            }else{
                ntf.setVisible(true);
                ntf.setText("Password Didn't Match Properly...!!");
            }
        }else{
            ntf.setVisible(true);
            ntf.setText("Some Fields Are Empty Please Fill Them Properly...!!");
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_createnewActionPerformed

    private void alreadyacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alreadyacActionPerformed
        dispose();
        login obj2=new login();
        obj2.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_alreadyacActionPerformed

    private void usrnmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usrnmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usrnmActionPerformed

    private void nmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nmActionPerformed

    private void ansActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ansActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ansActionPerformed

    private void usrtypActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usrtypActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usrtypActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        usrnm.setText("");
        nm.setText("");
        usrpss.setText("");
        usrrepss.setText("");
        ques.setSelectedItem("-----Select Any One-----");
        ans.setText("");
        usrtyp.setText("");
        ntf.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_clearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(usrreg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(usrreg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(usrreg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(usrreg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new usrreg().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alreadyac;
    private javax.swing.JTextField ans;
    private javax.swing.JButton clear;
    private javax.swing.JButton createnew;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nm;
    private javax.swing.JLabel ntf;
    private javax.swing.JComboBox<String> ques;
    private javax.swing.JTextField usrnm;
    private javax.swing.JPasswordField usrpss;
    private javax.swing.JPasswordField usrrepss;
    private javax.swing.JTextField usrtyp;
    // End of variables declaration//GEN-END:variables
}
